server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://youtube-synchronizer-mysql.ctocxlmg1uy5.ap-northeast-2.rds.amazonaws.com:3306/youtube_synchronizer?useUnicode=true&charaterEncoding=utf-8
    username: khs
    password: 12345677
    driver-class-name: com.mysql.jdbc.Driver
  devtools:
    restart:
      exclude: static/**,public/**
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL5Dialect

---
spring:
  profiles: prod
server:
  port: 80